-- 光伏预测 PostgreSQL 完整目标设计，版本 1。
-- 供审查或独立迁移使用；不要在 NocoBase 已建同名表后重复执行本文件。
-- NocoBase collections:create 只提交列、NOT NULL、主键、外键和索引；
-- 本文件的 CHECK 约束不会通过该接口自动落库，需独立迁移或写入服务校验。
-- SQL 使用当前 search_path；API 使用 NocoBase 主数据源配置的 schema。
-- SQL 使用 identity；API autoIncrement 的物理实现可能是 sequence/serial。
-- createdAt/updatedAt 由 NocoBase 接口管理，SQL 不创建更新时间触发器。
BEGIN;

CREATE TABLE "energy_weather_points" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "es_sn" text NOT NULL,
  "source_kind" text NOT NULL,
  "provider" text NOT NULL DEFAULT 'open_meteo',
  "source_batch_id" text NOT NULL,
  "weather_time" timestamptz NOT NULL,
  "interval_minutes" integer NOT NULL DEFAULT 60,
  "latitude" numeric(9,6) NOT NULL,
  "longitude" numeric(9,6) NOT NULL,
  "timezone" text NOT NULL DEFAULT 'Asia/Shanghai',
  "issued_at" timestamptz,
  "fetched_at" timestamptz,
  "temperature_c" numeric(7,3),
  "relative_humidity_pct" numeric(6,3),
  "cloud_cover_pct" numeric(6,3),
  "cloud_cover_low_pct" numeric(6,3),
  "cloud_cover_mid_pct" numeric(6,3),
  "cloud_cover_high_pct" numeric(6,3),
  "ghi_wm2" numeric(12,3),
  "direct_horizontal_wm2" numeric(12,3),
  "dhi_wm2" numeric(12,3),
  "precipitation_mm" numeric(10,3),
  "wind_speed_kmh" numeric(10,3),
  "quality_status" text NOT NULL DEFAULT 'unreviewed',
  "source_metadata" jsonb NOT NULL,
  "content_hash" text NOT NULL,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  CONSTRAINT "ewp_station_ck" CHECK (length(trim(es_sn)) > 0),
  CONSTRAINT "ewp_source_kind_ck" CHECK (source_kind IN ('historical_reanalysis', 'forecast')),
  CONSTRAINT "ewp_quality_ck" CHECK (quality_status IN ('unreviewed', 'valid', 'incomplete', 'invalid')),
  CONSTRAINT "ewp_identity_ck" CHECK (length(trim(provider)) > 0 AND source_batch_id ~ '^[0-9a-f]{64}$' AND content_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "ewp_hour_ck" CHECK (interval_minutes = 60 AND weather_time = date_trunc('hour', weather_time, 'UTC')),
  CONSTRAINT "ewp_availability_ck" CHECK ((source_kind <> 'forecast' OR fetched_at IS NOT NULL) AND (issued_at IS NULL OR fetched_at IS NULL OR issued_at <= fetched_at)),
  CONSTRAINT "ewp_metadata_ck" CHECK (jsonb_typeof(source_metadata) = 'object' AND length(trim(timezone)) > 0),
  CONSTRAINT "ewp_latitude_ck" CHECK ("latitude" > '-Infinity'::numeric AND "latitude" < 'Infinity'::numeric AND "latitude" >= -90 AND "latitude" <= 90),
  CONSTRAINT "ewp_longitude_ck" CHECK ("longitude" > '-Infinity'::numeric AND "longitude" < 'Infinity'::numeric AND "longitude" >= -180 AND "longitude" <= 180),
  CONSTRAINT "ewp_temperature_c_ck" CHECK ("temperature_c" > '-Infinity'::numeric AND "temperature_c" < 'Infinity'::numeric),
  CONSTRAINT "ewp_relative_humidity_pct_ck" CHECK ("relative_humidity_pct" > '-Infinity'::numeric AND "relative_humidity_pct" < 'Infinity'::numeric AND "relative_humidity_pct" >= 0 AND "relative_humidity_pct" <= 100),
  CONSTRAINT "ewp_cloud_cover_pct_ck" CHECK ("cloud_cover_pct" > '-Infinity'::numeric AND "cloud_cover_pct" < 'Infinity'::numeric AND "cloud_cover_pct" >= 0 AND "cloud_cover_pct" <= 100),
  CONSTRAINT "ewp_cloud_cover_low_pct_ck" CHECK ("cloud_cover_low_pct" > '-Infinity'::numeric AND "cloud_cover_low_pct" < 'Infinity'::numeric AND "cloud_cover_low_pct" >= 0 AND "cloud_cover_low_pct" <= 100),
  CONSTRAINT "ewp_cloud_cover_mid_pct_ck" CHECK ("cloud_cover_mid_pct" > '-Infinity'::numeric AND "cloud_cover_mid_pct" < 'Infinity'::numeric AND "cloud_cover_mid_pct" >= 0 AND "cloud_cover_mid_pct" <= 100),
  CONSTRAINT "ewp_cloud_cover_high_pct_ck" CHECK ("cloud_cover_high_pct" > '-Infinity'::numeric AND "cloud_cover_high_pct" < 'Infinity'::numeric AND "cloud_cover_high_pct" >= 0 AND "cloud_cover_high_pct" <= 100),
  CONSTRAINT "ewp_ghi_wm2_ck" CHECK ("ghi_wm2" > '-Infinity'::numeric AND "ghi_wm2" < 'Infinity'::numeric AND "ghi_wm2" >= 0),
  CONSTRAINT "ewp_direct_horizontal_wm2_ck" CHECK ("direct_horizontal_wm2" > '-Infinity'::numeric AND "direct_horizontal_wm2" < 'Infinity'::numeric AND "direct_horizontal_wm2" >= 0),
  CONSTRAINT "ewp_dhi_wm2_ck" CHECK ("dhi_wm2" > '-Infinity'::numeric AND "dhi_wm2" < 'Infinity'::numeric AND "dhi_wm2" >= 0),
  CONSTRAINT "ewp_precipitation_mm_ck" CHECK ("precipitation_mm" > '-Infinity'::numeric AND "precipitation_mm" < 'Infinity'::numeric AND "precipitation_mm" >= 0),
  CONSTRAINT "ewp_wind_speed_kmh_ck" CHECK ("wind_speed_kmh" > '-Infinity'::numeric AND "wind_speed_kmh" < 'Infinity'::numeric AND "wind_speed_kmh" >= 0),
  CONSTRAINT "ewp_finite_times_ck" CHECK (isfinite("weather_time") AND isfinite("issued_at") AND isfinite("fetched_at") AND isfinite("createdAt") AND isfinite("updatedAt"))
);
CREATE UNIQUE INDEX "ewp_batch_time_uq" ON "energy_weather_points" ("es_sn", "source_kind", "source_batch_id", "weather_time");
CREATE INDEX "ewp_station_time_idx" ON "energy_weather_points" ("es_sn", "source_kind", "weather_time");
CREATE INDEX "ewp_station_fetched_idx" ON "energy_weather_points" ("es_sn", "source_kind", "fetched_at");
COMMENT ON TABLE "energy_weather_points" IS '按电站、来源类型和批次保存小时天气，兼容现有历史CSV和未来天气预报，保留来源身份与时间语义。';
COMMENT ON COLUMN "energy_weather_points"."id" IS '主键';
COMMENT ON COLUMN "energy_weather_points"."es_sn" IS '电站编号。与 t_es_data.es_sn 对齐；当前为 ES02。';
COMMENT ON COLUMN "energy_weather_points"."source_kind" IS '天气来源类型。historical_reanalysis 或 forecast；历史再分析不得冒充当时的天气预报。';
COMMENT ON COLUMN "energy_weather_points"."provider" IS '天气提供方';
COMMENT ON COLUMN "energy_weather_points"."source_batch_id" IS '天气批次标识。来源文件或完整API响应及站点、坐标、时区、来源类型等身份元数据的SHA-256。相同批次重复导入使用同一标识。';
COMMENT ON COLUMN "energy_weather_points"."weather_time" IS '天气时间标签。辐照为该时刻前一小时均值，降雨为前一小时累计；温度、湿度、云量和风速为该整点瞬时值。';
COMMENT ON COLUMN "energy_weather_points"."interval_minutes" IS '天气间隔（分钟）';
COMMENT ON COLUMN "energy_weather_points"."latitude" IS '请求纬度';
COMMENT ON COLUMN "energy_weather_points"."longitude" IS '请求经度';
COMMENT ON COLUMN "energy_weather_points"."timezone" IS '来源时区';
COMMENT ON COLUMN "energy_weather_points"."issued_at" IS '预报发布时间。未知时保持NULL；导入历史CSV不得伪造发布时间。';
COMMENT ON COLUMN "energy_weather_points"."fetched_at" IS '原始数据获取时间。未来预报必须保留实际获取时间；现有CSV原下载时间未保存，保持NULL。';
COMMENT ON COLUMN "energy_weather_points"."temperature_c" IS '气温（℃）';
COMMENT ON COLUMN "energy_weather_points"."relative_humidity_pct" IS '相对湿度（%）';
COMMENT ON COLUMN "energy_weather_points"."cloud_cover_pct" IS '总云量（%）';
COMMENT ON COLUMN "energy_weather_points"."cloud_cover_low_pct" IS '低层云量（%）';
COMMENT ON COLUMN "energy_weather_points"."cloud_cover_mid_pct" IS '中层云量（%）';
COMMENT ON COLUMN "energy_weather_points"."cloud_cover_high_pct" IS '高层云量（%）';
COMMENT ON COLUMN "energy_weather_points"."ghi_wm2" IS '水平面总辐照（W/m²）';
COMMENT ON COLUMN "energy_weather_points"."direct_horizontal_wm2" IS '水平面直射辐照（W/m²）。对应Open-Meteo direct_radiation，不是DNI。';
COMMENT ON COLUMN "energy_weather_points"."dhi_wm2" IS '水平面散射辐照（W/m²）';
COMMENT ON COLUMN "energy_weather_points"."precipitation_mm" IS '前一小时降雨量（mm）';
COMMENT ON COLUMN "energy_weather_points"."wind_speed_kmh" IS '10米风速（km/h）。保留原CSV单位；调用需要m/s的模型时除以3.6。';
COMMENT ON COLUMN "energy_weather_points"."quality_status" IS '数据质量';
COMMENT ON COLUMN "energy_weather_points"."source_metadata" IS '来源元数据。保存文件名、文件SHA-256、请求模型选择、实际模型/网格信息（未知不填）、单位和时间语义版本；不得存凭据。';
COMMENT ON COLUMN "energy_weather_points"."content_hash" IS '本行内容哈希';
COMMENT ON COLUMN "energy_weather_points"."createdAt" IS '创建时间';
COMMENT ON COLUMN "energy_weather_points"."updatedAt" IS '更新时间';

CREATE TABLE "energy_pv_forecast_runs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_id" text NOT NULL,
  "es_sn" text NOT NULL,
  "run_kind" text NOT NULL,
  "as_of" timestamptz NOT NULL,
  "forecast_start" timestamptz NOT NULL,
  "forecast_end" timestamptz NOT NULL,
  "interval_minutes" integer NOT NULL DEFAULT 15,
  "expected_points" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'queued',
  "model_name" text,
  "model_version" text,
  "model_config" jsonb NOT NULL,
  "training_start" timestamptz,
  "training_end" timestamptz,
  "pv_history_end" timestamptz,
  "weather_batch_id" text,
  "weather_source_kind" text,
  "source_manifest" jsonb NOT NULL,
  "evaluation_metrics" jsonb,
  "bounds_coverage_pct" numeric(6,3),
  "generated_at" timestamptz,
  "error_code" text,
  "content_hash" text,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  CONSTRAINT "epfr_identity_ck" CHECK (length(trim(es_sn)) > 0 AND run_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  CONSTRAINT "epfr_kind_ck" CHECK (run_kind IN ('operational', 'backtest')),
  CONSTRAINT "epfr_weather_kind_ck" CHECK (weather_source_kind IS NULL OR weather_source_kind IN ('historical_reanalysis', 'forecast')),
  CONSTRAINT "epfr_status_ck" CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  CONSTRAINT "epfr_window_ck" CHECK (interval_minutes = 15 AND expected_points > 0 AND forecast_end > forecast_start AND as_of <= forecast_start AND forecast_end = forecast_start + expected_points * interval '15 minutes' AND mod(extract(epoch FROM forecast_start), 900) = 0),
  CONSTRAINT "epfr_training_ck" CHECK ((training_start IS NULL AND training_end IS NULL) OR (training_start IS NOT NULL AND training_end IS NOT NULL AND training_start < training_end AND training_end <= as_of)),
  CONSTRAINT "epfr_history_ck" CHECK (pv_history_end <= as_of),
  CONSTRAINT "epfr_hash_ck" CHECK ((weather_batch_id IS NULL OR weather_batch_id ~ '^[0-9a-f]{64}$') AND (content_hash IS NULL OR content_hash ~ '^[0-9a-f]{64}$')),
  CONSTRAINT "epfr_json_ck" CHECK (jsonb_typeof(model_config) = 'object' AND jsonb_typeof(source_manifest) = 'object' AND (evaluation_metrics IS NULL OR jsonb_typeof(evaluation_metrics) = 'object')),
  CONSTRAINT "epfr_coverage_ck" CHECK ("bounds_coverage_pct" > '-Infinity'::numeric AND "bounds_coverage_pct" < 'Infinity'::numeric AND "bounds_coverage_pct" >= 0.001 AND "bounds_coverage_pct" <= 99.999),
  CONSTRAINT "epfr_generated_ck" CHECK (generated_at >= as_of),
  CONSTRAINT "epfr_completed_ck" CHECK (status <> 'completed' OR (model_name IS NOT NULL AND length(trim(model_name)) > 0 AND model_version IS NOT NULL AND length(trim(model_version)) > 0 AND weather_batch_id IS NOT NULL AND weather_source_kind IS NOT NULL AND generated_at IS NOT NULL AND content_hash IS NOT NULL AND error_code IS NULL)),
  CONSTRAINT "epfr_operational_ck" CHECK (status <> 'completed' OR run_kind <> 'operational' OR weather_source_kind = 'forecast'),
  CONSTRAINT "epfr_failed_ck" CHECK (status <> 'failed' OR error_code IS NOT NULL),
  CONSTRAINT "epfr_finite_times_ck" CHECK (isfinite("as_of") AND isfinite("forecast_start") AND isfinite("forecast_end") AND isfinite("training_start") AND isfinite("training_end") AND isfinite("pv_history_end") AND isfinite("generated_at") AND isfinite("createdAt") AND isfinite("updatedAt"))
);
CREATE UNIQUE INDEX "epfr_run_id_uq" ON "energy_pv_forecast_runs" ("run_id");
CREATE INDEX "epfr_station_status_asof_idx" ON "energy_pv_forecast_runs" ("es_sn", "run_kind", "status", "as_of");
COMMENT ON TABLE "energy_pv_forecast_runs" IS '记录模型、训练窗口、天气批次、信息截止时间和发布状态，支持原始预测追溯与离线回测。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."id" IS '主键';
COMMENT ON COLUMN "energy_pv_forecast_runs"."run_id" IS '预测批次UUID';
COMMENT ON COLUMN "energy_pv_forecast_runs"."es_sn" IS '电站编号';
COMMENT ON COLUMN "energy_pv_forecast_runs"."run_kind" IS '运行用途。operational 为实际预测；backtest 为历史回测或同输入回算。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."as_of" IS '可用信息截止时间。每条实际使用的历史功率采样、天气发布时间/获取时间都必须不晚于此时间；事后天气回测必须另行标明。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."forecast_start" IS '预测区间开始';
COMMENT ON COLUMN "energy_pv_forecast_runs"."forecast_end" IS '预测区间结束（不含）';
COMMENT ON COLUMN "energy_pv_forecast_runs"."interval_minutes" IS '预测间隔（分钟）';
COMMENT ON COLUMN "energy_pv_forecast_runs"."expected_points" IS '应有预测点数';
COMMENT ON COLUMN "energy_pv_forecast_runs"."status" IS '运行状态';
COMMENT ON COLUMN "energy_pv_forecast_runs"."model_name" IS '模型名称';
COMMENT ON COLUMN "energy_pv_forecast_runs"."model_version" IS '模型版本';
COMMENT ON COLUMN "energy_pv_forecast_runs"."model_config" IS '模型参数';
COMMENT ON COLUMN "energy_pv_forecast_runs"."training_start" IS '实际训练数据开始';
COMMENT ON COLUMN "energy_pv_forecast_runs"."training_end" IS '实际训练数据结束（不含）';
COMMENT ON COLUMN "energy_pv_forecast_runs"."pv_history_end" IS '最新实测功率采样时间';
COMMENT ON COLUMN "energy_pv_forecast_runs"."weather_batch_id" IS '本次使用的天气批次。引用energy_weather_points.source_batch_id；它是一批多行，不是唯一外键。写入服务校验站点和完整覆盖。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."weather_source_kind" IS '本次天气来源类型';
COMMENT ON COLUMN "energy_pv_forecast_runs"."source_manifest" IS '输入来源与快照清单。包含天气批次/来源类型/实际使用行哈希、实际使用的聚合光伏输入快照或不可变快照引用、聚合与缺失规则；仅窗口和哈希不能还原输入。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."evaluation_metrics" IS '评估指标与口径。保存评估窗口、预测步长、白天/全天、样本覆盖率、MAE/RMSE等；无评估保持NULL。';
COMMENT ON COLUMN "energy_pv_forecast_runs"."bounds_coverage_pct" IS '预测区间名义覆盖率（%）';
COMMENT ON COLUMN "energy_pv_forecast_runs"."generated_at" IS '预测生成完成时间';
COMMENT ON COLUMN "energy_pv_forecast_runs"."error_code" IS '失败原因代码';
COMMENT ON COLUMN "energy_pv_forecast_runs"."content_hash" IS '本批预测内容哈希';
COMMENT ON COLUMN "energy_pv_forecast_runs"."createdAt" IS '创建时间';
COMMENT ON COLUMN "energy_pv_forecast_runs"."updatedAt" IS '更新时间';

CREATE TABLE "energy_pv_forecast_points" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "run_pk" bigint NOT NULL,
  "target_time" timestamptz NOT NULL,
  "horizon_step" integer NOT NULL,
  "forecast_kw" numeric(14,6) NOT NULL,
  "raw_forecast_kw" numeric(14,6),
  "baseline_kw" numeric(14,6),
  "lower_kw" numeric(14,6),
  "upper_kw" numeric(14,6),
  "is_clipped" boolean NOT NULL DEFAULT FALSE,
  "createdAt" timestamptz,
  "updatedAt" timestamptz,
  CONSTRAINT "epfp_run_fk" FOREIGN KEY ("run_pk") REFERENCES "energy_pv_forecast_runs" ("id") ON DELETE RESTRICT,
  CONSTRAINT "epfp_time_step_ck" CHECK (horizon_step > 0 AND mod(extract(epoch FROM target_time), 900) = 0),
  CONSTRAINT "epfp_forecast_ck" CHECK ("forecast_kw" > '-Infinity'::numeric AND "forecast_kw" < 'Infinity'::numeric AND "forecast_kw" >= 0),
  CONSTRAINT "epfp_raw_ck" CHECK ("raw_forecast_kw" > '-Infinity'::numeric AND "raw_forecast_kw" < 'Infinity'::numeric),
  CONSTRAINT "epfp_baseline_ck" CHECK ("baseline_kw" > '-Infinity'::numeric AND "baseline_kw" < 'Infinity'::numeric AND "baseline_kw" >= 0),
  CONSTRAINT "epfp_lower_ck" CHECK ("lower_kw" > '-Infinity'::numeric AND "lower_kw" < 'Infinity'::numeric AND "lower_kw" >= 0),
  CONSTRAINT "epfp_upper_ck" CHECK ("upper_kw" > '-Infinity'::numeric AND "upper_kw" < 'Infinity'::numeric AND "upper_kw" >= 0),
  CONSTRAINT "epfp_bounds_ck" CHECK ((lower_kw IS NULL AND upper_kw IS NULL) OR (lower_kw IS NOT NULL AND upper_kw IS NOT NULL AND lower_kw <= forecast_kw AND forecast_kw <= upper_kw)),
  CONSTRAINT "epfp_finite_times_ck" CHECK (isfinite("target_time") AND isfinite("createdAt") AND isfinite("updatedAt"))
);
CREATE UNIQUE INDEX "epfp_run_time_uq" ON "energy_pv_forecast_points" ("run_pk", "target_time");
CREATE UNIQUE INDEX "epfp_run_step_uq" ON "energy_pv_forecast_points" ("run_pk", "horizon_step");
CREATE INDEX "epfp_target_time_idx" ON "energy_pv_forecast_points" ("target_time");
COMMENT ON TABLE "energy_pv_forecast_points" IS '每批次每15分钟一条平均交流功率；通过run_pk关联批次，实测继续使用t_es_data，缺失预测不填零。';
COMMENT ON COLUMN "energy_pv_forecast_points"."id" IS '主键';
COMMENT ON COLUMN "energy_pv_forecast_points"."run_pk" IS '预测批次主键';
COMMENT ON COLUMN "energy_pv_forecast_points"."target_time" IS '15分钟区间开始时间';
COMMENT ON COLUMN "energy_pv_forecast_points"."horizon_step" IS '预测步数（从1开始）';
COMMENT ON COLUMN "energy_pv_forecast_points"."forecast_kw" IS '区间平均交流光伏功率（kW）';
COMMENT ON COLUMN "energy_pv_forecast_points"."raw_forecast_kw" IS '约束处理前预测功率（kW）';
COMMENT ON COLUMN "energy_pv_forecast_points"."baseline_kw" IS '同批次七日参考功率（kW）';
COMMENT ON COLUMN "energy_pv_forecast_points"."lower_kw" IS '预测区间下界（kW）';
COMMENT ON COLUMN "energy_pv_forecast_points"."upper_kw" IS '预测区间上界（kW）';
COMMENT ON COLUMN "energy_pv_forecast_points"."is_clipped" IS '是否经过边界截断';
COMMENT ON COLUMN "energy_pv_forecast_points"."createdAt" IS '创建时间';
COMMENT ON COLUMN "energy_pv_forecast_points"."updatedAt" IS '更新时间';

COMMIT;
