'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawn}=require('node:child_process');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const host=spawn(path.join(root,'.venv/bin/python'),['tests/m4_selection_demo_server.py'],{cwd:root});
 let browser,release;const errors=[];
 try{
  const clock=await new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(Error('server startup timeout')),15000);host.stdout.on('data',chunk=>{text+=chunk;const match=text.match(/PORT=(\d+) CLOCK=(\d+)/);if(match){clearTimeout(timer);resolve({port:Number(match[1]),now:Number(match[2])});}});host.once('exit',code=>reject(Error('server exit '+code)));host.stderr.on('data',chunk=>process.stderr.write(chunk));});
  const port=clock.port,url=`http://127.0.0.1:${port}/m4`;
  for(let i=0;i<30;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(now=>{Date.now=()=>now;},clock.now);
  await page.goto(url);await page.waitForLoadState('networkidle');
  await page.waitForSelector('#selection-panel');
  assert.match(await page.locator('#selection-status').innerText(),/待配置/);
  await page.locator('#open-selection-policy').click();await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('#policy-metric').inputValue(),'');
  await page.selectOption('#policy-metric','energy_cost');
  for(const id of ['policy-peak-tolerance','policy-energy-tolerance','policy-metric-tolerance'])await page.locator('#'+id).fill('0.000001');
  for(const [index,value] of ['cost','balanced','pv'].entries())await page.selectOption('#policy-tie-'+index,value);
  await page.locator('#save-selection-policy').click();
  await page.waitForFunction(()=>document.querySelector('#policy-status').dataset.state==='saved');
  await page.locator('#close-selection-policy').click();
  assert.match(await page.locator('#selection-status').innerText(),/待选择|候选/);
  if(await page.locator('#start-live-candidates').isDisabled())console.log('INPUT GATE:',await page.locator('#live-input-panel').innerText());
  await page.locator('#start-live-candidates').click();
  await page.waitForFunction(()=>document.querySelector('#live-candidate-status').dataset.state==='ready');
  await page.locator('#select-candidate').click();
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state==='selected');
  assert.match(await page.locator('#selection-summary').innerText(),/净电费/);
  assert.match(await page.locator('#decision-confidence').innerText(),/未下发/);
  assert.equal(await page.locator('[data-program-selected="true"]').count(),1);
  await page.locator('#selection-audit').evaluate(e=>e.open=true);
  assert.match(await page.locator('#selection-audit').innerText(),/计划版本|需量/);
  const screenshots=process.env.M4_SELECTION_SCREENSHOT_DIR;
  if(screenshots){fs.mkdirSync(screenshots,{recursive:true});for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);await page.screenshot({animations:'disabled',path:path.join(screenshots,`selection-${width}-${theme}.png`),fullPage:true});}}}
  await page.setViewportSize({width:1440,height:1100});
  await page.selectOption('#station-select','s2');assert.match(await page.locator('#selection-status').innerText(),/待配置/);
  await page.selectOption('#station-select','s1');assert.equal(await page.locator('#selection-status').getAttribute('data-state'),'selected');
  await page.locator('#open-selection-policy').click();await page.waitForLoadState('networkidle');
  if(screenshots){for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.equal(await page.locator('#selection-policy-drawer').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.screenshot({animations:'disabled',path:path.join(screenshots,`policy-${width}-${theme}.png`)});}}}
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#clear-selection-policy').click();await page.waitForFunction(()=>document.querySelector('#policy-status').dataset.state==='saved');
  await page.locator('#close-selection-policy').click();assert.match(await page.locator('#selection-status').innerText(),/待配置/);
  assert.equal(await page.locator('[data-program-selected="true"]').count(),0);
  await page.reload();await page.waitForLoadState('networkidle');assert.match(await page.locator('#selection-status').innerText(),/待配置/);
  // A background refresh must not silently upgrade the revision of an open draft.
  await page.locator('#open-selection-policy').click();await page.waitForLoadState('networkidle');
  await page.selectOption('#policy-metric','energy_cost');
  for(const id of ['policy-peak-tolerance','policy-energy-tolerance','policy-metric-tolerance'])await page.locator('#'+id).fill('0.000001');
  for(const [index,value] of ['cost','balanced','pv'].entries())await page.selectOption('#policy-tie-'+index,value);
  const endpoint=`http://127.0.0.1:${port}/m4-api/stations/station-1/selection-policy`;
  const before=await(await page.request.get(endpoint)).json();
  const preferences={metric:'preferred_soc_deviation',demand_peak_tolerance_kw:0.000001,demand_energy_tolerance_kwh:0.000001,metric_tolerance:0.000001,tie_order:['balanced','cost','pv']};
  const updated=await(await page.request.put(endpoint,{data:{expected_revision:before.revision,preferences}})).json();
  await page.waitForResponse(async response=>response.url()===endpoint&&response.request().method()==='GET'&&(await response.json()).revision===updated.revision,{timeout:15000});
  await page.locator('#save-selection-policy').click();
  await page.waitForFunction(()=>document.querySelector('#policy-status').dataset.state==='error');
  assert.match(await page.locator('#policy-status').innerText(),/其他窗口更新/);
  assert.equal((await(await page.request.get(endpoint)).json()).revision,updated.revision);
  await page.locator('#reload-selection-policy').click();
  await page.waitForFunction(()=>document.querySelector('#policy-metric').value==='preferred_soc_deviation');
  await page.locator('#close-selection-policy').click();
  if(await page.locator('#start-live-candidates').isDisabled())console.log('INPUT GATE:',await page.locator('#live-input-panel').innerText());
  await page.locator('#start-live-candidates').click();
  await page.waitForFunction(()=>document.querySelector('#live-candidate-status').dataset.state==='ready');
  await page.locator('#select-candidate').click();
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state==='selected');
  const currentSettings=await(await page.request.get(`http://127.0.0.1:${port}/m4-api/stations/station-1/settings`)).json();
  const newRun=await page.request.post(`http://127.0.0.1:${port}/m4-api/stations/station-1/candidates`,{data:{configuration_version:currentSettings.version}});
  assert.equal(newRun.status(),200);
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state!=='selected',{},{timeout:15000});
  assert.equal(await page.locator('[data-program-selected="true"]').count(),0);
  await page.locator('#start-live-candidates').click();
  await page.waitForFunction(()=>document.querySelector('#live-candidate-status').dataset.state==='ready');
  let heldResolve;const held=new Promise(resolve=>heldResolve=resolve);
  await page.route('**/station-1/selection',async route=>{const response=await route.fetch();await new Promise(resolve=>{release=resolve;heldResolve();});await route.fulfill({response});});
  await page.locator('#select-candidate').click();await held;
  await page.locator('#refresh-live-inputs').click();await page.waitForFunction(()=>document.querySelector('#live-input-status').dataset.state==='ready');
  release();release=null;await page.waitForLoadState('networkidle');
  assert.notEqual(await page.locator('#selection-status').getAttribute('data-state'),'selected');
  assert.equal(await page.locator('[data-program-selected="true"]').count(),0);
  await page.unroute('**/station-1/selection');
  // A failed server-version check must clear a previously selected preview.
  await page.locator('#start-live-candidates').click();
  await page.waitForFunction(()=>document.querySelector('#live-candidate-status').dataset.state==='ready');
  await page.locator('#select-candidate').click();
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state==='selected');
  await page.route('**/station-1/candidates',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'temporary candidate read failure'})}));
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state!=='selected',{},{timeout:15000});
  assert.match(await page.locator('#selection-summary').innerText(),/复核失败/);
  assert.equal(await page.locator('[data-program-selected="true"]').count(),0);
  await page.unroute('**/station-1/candidates');
  // Profile preference means balanced by name, independent of SOC or cost metrics.
  await page.locator('#open-selection-policy').click();await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('#policy-metric option[value="profile_priority"]').count(),1);
  await page.selectOption('#policy-metric','profile_priority');
  assert.equal(await page.locator('#policy-metric-tolerance').inputValue(),'0');
  assert.equal(await page.locator('#policy-metric-tolerance').isDisabled(),true);
  for(const id of ['policy-peak-tolerance','policy-energy-tolerance'])await page.locator('#'+id).fill('0');
  for(const [index,value] of ['balanced','cost','pv'].entries())await page.selectOption('#policy-tie-'+index,value);
  await page.locator('#save-selection-policy').click();
  await page.waitForFunction(()=>document.querySelector('#policy-status').dataset.state==='saved');
  const profilePolicy=(await(await page.request.get(endpoint)).json()).policy;
  assert.equal(profilePolicy.metric,'profile_priority');assert.equal(profilePolicy.metric_tolerance,0);
  assert.deepEqual(profilePolicy.tie_order,['balanced','cost','pv']);
  if(screenshots){for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1100});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({animations:'disabled',path:path.join(screenshots,`profile-policy-${width}-${theme}.png`)});assert.equal(await page.locator('#selection-policy-drawer').evaluate(e=>e.scrollWidth<=e.clientWidth),true);}}}
  await page.setViewportSize({width:1440,height:1100});await page.locator('#close-selection-policy').click();
  await page.locator('#start-live-candidates').click();
  await page.waitForFunction(()=>document.querySelector('#live-candidate-status').dataset.state==='ready');
  const selectedResponse=page.waitForResponse(response=>response.url().endsWith('/station-1/selection')&&response.request().method()==='POST');
  await page.locator('#select-candidate').click();
  const profileSelection=(await(await selectedResponse).json()).selection;
  await page.waitForFunction(()=>document.querySelector('#selection-status').dataset.state==='selected');
  assert.equal(profileSelection.selector_version,'demand-then-profile-v1');
  assert.equal(profileSelection.selected.profile_id,['balanced','cost','pv'].find(id=>profileSelection.steps[1].remaining_ids.includes(id)));
  assert.match(await page.locator('#selection-summary').innerText(),/候选顺序/);
  await page.reload();await page.waitForLoadState('networkidle');
  await page.locator('#open-selection-policy').click();await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('#policy-metric').inputValue(),'profile_priority');
  assert.equal(await page.locator('#policy-metric-tolerance').isDisabled(),true);
  await page.selectOption('#policy-metric','energy_cost');
  assert.equal(await page.locator('#policy-metric-tolerance').isDisabled(),false);
  assert.equal(await page.locator('#policy-metric-tolerance').inputValue(),'');
  assert.deepEqual(errors,[]);
  console.log('PASS: local API/solver, policy save/select/clear, conflict, cross-window candidate update, failed recheck, late response, station isolation, audit and responsive themes.');
 }finally{if(release)release();if(browser)await browser.close();host.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
