const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('m4/web/M4优化调度控制台-线上版.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const source=script.slice(script.indexOf('function renderEMSTableWrite('),script.indexOf('async function loadCurrent('));
const elements={};const context=vm.createContext({$:id=>elements[id]??=( {} ),timeText:t=>t});vm.runInContext(source,context);
const job={ems_table_write:{enabled:true,network_write_performed:true,status:'plan_table_readback_verified',effective_at:'14:15',operation_counts:{create:2,update:1,destroy:3}}};
context.renderEMSTableWrite(job);assert.equal(elements['ems-table-status'].textContent,'计划表已写入');assert.match(elements['ems-table-context'].textContent,/设备执行未核实/);
context.renderEMSTableWrite({...job,ems_table_write:{...job.ems_table_write,status:'table_write_unconfirmed',reason:'等待核对'}});assert.equal(elements['ems-table-status'].textContent,'写入待核对');assert.equal(elements['ems-table-detail'].textContent,'等待核对');
context.renderEMSTableWrite({...job,rolling:{result:{ems_table_write:{status:'blocked',reason:'需量超限'}}}});assert.equal(elements['ems-table-status'].textContent,'写入已阻断');
context.renderEMSTableWrite({...job,ems_table_write:{...job.ems_table_write,network_write_performed:false}});assert.equal(elements['ems-table-status'].textContent,'计划表已核对');
context.renderEMSTableWrite(null);assert.equal(elements['ems-table-status'].textContent,'状态暂不可用');
console.log('EMS table UI: verified, uncertain, blocked and missing states passed');
