"""Browser scenarios generated by the same read-only arithmetic as the API."""
import json
from pathlib import Path
from m4.optimizer.contracts import OptimizationRequest, CandidateResult
from m4.settings.peak_preparation import summarize_peak_preparation
from m4.tests.test_m4_peak_preparation import scenario

root=Path(__file__).resolve().parents[2]
request=OptimizationRequest.model_validate_json((root/'m4/mock/orchestration/station-1.json').read_text())
result=json.loads((root/'m4/mock/orchestration/orchestration-result.json').read_text())
candidate=CandidateResult.model_validate_json(json.dumps(result['stations'][0]['optimization_result']['candidates'][0]))
views={'covered':(request,candidate),'energy':scenario({0:140,1:140}),
       'power':scenario({0:300},soc=90,eta_d=1),'clear':scenario()}
output={}
for name,(request,candidate) in views.items():
    request=request.model_copy(update={'station_id':'station-1'})
    output[name]={'summary':summarize_peak_preparation(request,candidate),
                  'candidate':candidate.model_dump(mode='json')}
print(json.dumps(output))
