const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('m4/web/M4优化调度控制台-线上版.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const extract=(a,b)=>script.slice(script.indexOf(a),script.indexOf(b,script.indexOf(a)));
const nodes=new Map();
let clears=0;
const $=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',innerHTML:'',replaceChildren(){clears++;this.innerHTML='';}});return nodes.get(id);};
$('station').value='station-2';$('plan-date').value='2026-09-16';
let now=Date.parse('2026-09-16T10:00:00+08:00');
class Clock extends Date {static now(){return now;}}
const job={station_id:'station-2',status:'completed',result:{station_id:'station-2',date:'2026-09-16',schema_version:'m4-rolling-plan-v1',dispatch_status:'not_dispatched',valid_until:'2026-09-16T10:15:00+08:00',effective_at:'2026-09-16T10:00:00+08:00',source:'optimized',reason:'后续建议',anchor:{measured_soc_pct:50,projected_soc_pct:49},plan:[{timestamp:'2026-09-16T10:00:00+08:00',mode:'discharge',target_power_kw:100,expected_soc_pct:48}]}};
const ctx=vm.createContext({$,Date:Clock,JSON,rollingAdvice:job,rollingHistory:null,today:()=> '2026-09-16',finite:Number.isFinite,fmt:String,esc:String,clock:String,timeText:String,renderChart(){},renderInspector(){},renderScheduleTable(){},clearTimeout(){},generation:0,pollTimer:null,context:null,sessionStorage:{setItem(){}},plan:{station:'station-2',date:'2026-09-16'},restoreView:()=>false,setLoading(){},clearPlan(){},readCurrent:()=>new Promise(()=>{})});
vm.runInContext(extract('function currentRollingPayload(){','function rollingGroups'),ctx);
vm.runInContext(extract('let rollingRenderKey=null;','setInterval(renderRollingAdvice'),ctx);
vm.runInContext(extract('async function loadCurrent(){','function renderBaseline'),ctx);
vm.runInContext('renderRollingAdvice()',ctx);
const markup=$('rolling-rows').innerHTML;
assert.match(markup,/放电/);
vm.runInContext('renderRollingAdvice();loadCurrent();',ctx);
assert.equal(clears,1,'same-scope refresh must not clear or rebuild advice');
assert.equal($('rolling-rows').innerHTML,markup);
now+=16*60*1000;
vm.runInContext('renderRollingAdvice()',ctx);
assert.match($('rolling-rows').innerHTML,/暂无有效后续建议/);
now-=16*60*1000;
vm.runInContext('renderRollingAdvice()',ctx);
$('station').value='station-1';
vm.runInContext('loadCurrent()',ctx);
assert.equal(ctx.rollingAdvice,null,'station switch must clear prior station advice');
$('station').value='station-2';ctx.rollingAdvice=job;vm.runInContext('renderRollingAdvice()',ctx);
ctx.rollingAdvice={station_id:'station-2',status:'stale',message:'日计划已更新'};
vm.runInContext('renderRollingAdvice()',ctx);
assert.match($('rolling-rows').innerHTML,/暂无有效后续建议/);
assert.equal($('rolling-context').textContent,'日计划已更新');
console.log('Rolling refresh: preserve, unchanged render, expiry, station switch and invalidation passed');
