#!/usr/bin/env python3
"""Render/review the PV schema; optionally create exactly three NocoBase tables.

No runtime credentials are read by default. --execute requires a dedicated
schema credential, preflights every name, creates once, and verifies metadata.
It never changes roles, modifies existing collections, or deletes anything.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


schema = module('pv_forecast_schema', ROOT / 'contracts/pv_forecast_schema.py')
base = module('m3_schema_deployment', ROOT / 'scripts/create-custom-forecast-collections.py')


def quote(identifier):
    if re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', identifier) is None:
        raise ValueError('invalid_identifier')
    return '"' + identifier + '"'


def literal(value):
    if type(value) is bool:
        return 'TRUE' if value else 'FALSE'
    if type(value) is int:
        return str(value)
    if type(value) is str:
        return "'" + value.replace("'", "''") + "'"
    raise ValueError('unsupported_default')


def payloads():
    result = []
    for table in schema.TABLES:
        fields = []
        for item in table['fields']:
            name = item['name']
            base.FIELD_TITLES[name] = item['title']
            definition = {k: item[k] for k in ('type', 'nullable')}
            if name == 'id':
                definition.update(primary_key=True, identity=True)
            if name in ('createdAt', 'updatedAt'):
                management = {'on_create': 'current_timestamp'}
                if name == 'updatedAt':
                    management['on_update'] = 'current_timestamp'
                definition.update(client_writable=False, interface=name, server_managed=management)
            field = base.field_payload(name, definition)
            if 'default' in item:
                field['defaultValue'] = item['default']
            if item.get('description'):
                field['description'] = item['description']
                field['comment'] = item['description']
            fields.append(field)
        if relation := table.get('relationship'):
            fields.append({
                'name': relation['name'], 'type': 'belongsTo', 'interface': 'm2o',
                'target': relation['target'], 'foreignKey': relation['foreignKey'],
                'targetKey': relation['targetKey'], 'onDelete': relation['onDelete'], 'constraints': True,
                'uiSchema': {'title': relation['title'], 'x-component': 'AssociationField',
                             'x-component-props': {'multiple': False}},
            })
        result.append({
            'name': table['name'], 'title': table['title'], 'description': table['description'],
            'autoGenId': False, 'timestamps': False, 'createdAt': False, 'updatedAt': False,
            'createdBy': False, 'updatedBy': False, 'sortable': False, 'filterTargetKey': 'id',
            'fields': fields, 'indexes': table['indexes'],
        })
    return result


def sql_text():
    lines = [
        '-- 光伏预测 PostgreSQL 完整目标设计，版本 1。',
        '-- 供审查或独立迁移使用；不要在 NocoBase 已建同名表后重复执行本文件。',
        '-- NocoBase collections:create 只提交列、NOT NULL、主键、外键和索引；',
        '-- 本文件的 CHECK 约束不会通过该接口自动落库，需独立迁移或写入服务校验。',
        '-- SQL 使用当前 search_path；API 使用 NocoBase 主数据源配置的 schema。',
        '-- SQL 使用 identity；API autoIncrement 的物理实现可能是 sequence/serial。',
        '-- createdAt/updatedAt 由 NocoBase 接口管理，SQL 不创建更新时间触发器。',
        'BEGIN;', '',
    ]
    for table in schema.TABLES:
        definitions = []
        for field in table['fields']:
            definition = f'  {quote(field["name"])} {field["type"]}'
            if field['name'] == 'id':
                definition += ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            elif not field['nullable']:
                definition += ' NOT NULL'
            if 'default' in field:
                definition += ' DEFAULT ' + literal(field['default'])
            definitions.append(definition)
        if relation := table.get('relationship'):
            definitions.append(f'  CONSTRAINT "epfp_run_fk" FOREIGN KEY ({quote(relation["foreignKey"])}) REFERENCES {quote(relation["target"])} ({quote(relation["targetKey"])}) ON DELETE {relation["onDelete"]}')
        for name, expression in table['checks']:
            definitions.append(f'  CONSTRAINT {quote(name)} CHECK ({expression})')
        lines += [f'CREATE TABLE {quote(table["name"])} (', ',\n'.join(definitions), ');']
        for index in table['indexes']:
            unique = 'UNIQUE ' if index['unique'] else ''
            columns = ', '.join(quote(name) for name in index['fields'])
            lines.append(f'CREATE {unique}INDEX {quote(index["name"])} ON {quote(table["name"])} ({columns});')
        lines.append(f'COMMENT ON TABLE {quote(table["name"])} IS {literal(table["description"])};')
        for field in table['fields']:
            description = field['title'] + ('。' + field['description'] if field.get('description') else '')
            lines.append(f'COMMENT ON COLUMN {quote(table["name"])}.{quote(field["name"])} IS {literal(description)};')
        lines.append('')
    return '\n'.join(lines + ['COMMIT;', ''])


def schema_credential():
    key = os.environ.get('PV_NOCOBASE_SCHEMA_API_KEY', '').strip()
    token_file = os.environ.get('PV_NOCOBASE_SCHEMA_API_KEY_FILE', '').strip()
    if bool(key) == bool(token_file):
        raise base.DeploymentError('请配置且仅配置 PV_NOCOBASE_SCHEMA_API_KEY 或 PV_NOCOBASE_SCHEMA_API_KEY_FILE；不复用业务查询凭据。')
    value = key if key else base.read_token_file(token_file)
    if base.TOKEN.fullmatch(value) is None:
        raise base.DeploymentError('建表凭据格式无效')
    return value


def verify(actual, expected):
    base.verify_collection(actual, expected)
    fields = {f['name']: f for f in actual['fields']}
    for field in expected['fields']:
        if 'defaultValue' in field and fields[field['name']].get('defaultValue') != field['defaultValue']:
            raise base.DeploymentError(f'{expected["name"]}.{field["name"]} 默认值回读不一致')


def deploy(expected, *, verify_only=False):
    client = base.NocoBaseSchemaClient(schema.BASE_URL, schema_credential(), timeout_seconds=20, max_response_bytes=4*1024*1024)
    # Preflight every name before the first mutation; never infer absence from 403.
    existing = {item['name']: client.get_collection(item['name']) for item in expected}
    if verify_only:
        for item in expected:
            if existing[item['name']] is None:
                raise base.DeploymentError(f'集合尚不存在：{item["name"]}')
            verify(existing[item['name']], item)
        return {'verified_metadata': [p['name'] for p in expected], 'physical_check_constraints_verified': False}
    found = [name for name, value in existing.items() if value is not None]
    if found:
        raise base.DeploymentError('存在同名集合，未创建任何表：' + ', '.join(found))
    created = []
    for item in expected:
        # An uncertain POST is not retried. Re-read this name before any manual continuation.
        print(json.dumps({'creating': item['name'], 'previously_verified': created}), flush=True)
        client.create_collection(item)
        actual = client.get_collection(item['name'])
        if actual is None:
            raise base.DeploymentError('创建后未能回读集合：' + item['name'])
        verify(actual, item)
        created.append(item['name'])
    return {'created_and_verified_metadata': created, 'physical_check_constraints_applied': False,
            'data_imported': False, 'forecasting_logic_changed': False}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument('--execute', action='store_true', help='通过固定项目源创建三张表')
    actions.add_argument('--verify-only', action='store_true', help='仅回读并比较三张表的元数据')
    parser.add_argument('--write-artifacts', action='store_true', help='写出SQL和collections:create请求JSON；不联网')
    args = parser.parse_args()
    expected = payloads()
    if args.write_artifacts:
        (ROOT / 'contracts/pv_forecast_schema.sql').write_text(sql_text(), encoding='utf-8')
        (ROOT / 'contracts/pv_forecast_nocobase_payloads.json').write_text(
            json.dumps({'version': schema.VERSION, 'endpoint': schema.BASE_URL+'/api/collections:create',
                        'method': 'POST', 'collections': expected,
                        'not_applied_by_api': ['physical CHECK constraints', 'cross-table forecast completeness/availability invariants']},
                       ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    if args.execute or args.verify_only:
        print(json.dumps(deploy(expected, verify_only=args.verify_only), ensure_ascii=False, indent=2))
    else:
        print(json.dumps({'mode': 'offline', 'tables': [{'name': p['name'], 'fields': len(p['fields']), 'indexes': len(p['indexes'])} for p in expected],
                          'physical_checks_in_sql_only': sum(len(t['checks']) for t in schema.TABLES)}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    try:
        main()
    except base.DeploymentError as error:
        # The reused client emits controlled messages only, never response bodies or tokens.
        print(json.dumps({'error': str(error), 'automatic_retry': False}, ensure_ascii=False))
        sys.exit(1)
    except Exception as error:
        print(json.dumps({'error': type(error).__name__, 'automatic_retry': False}))
        sys.exit(1)
